# Generated by Django 4.1.9 on 2023-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
